## Indexation normale

In [1]:
import numpy as np
import pandas as pd

In [8]:
arr= np.array([[[1,2,7],[3,4,8]],[[4,9,2],[5,3,1]]])
arr.ndim
arr[1] # deuxieme matrice
arr[1][0] # premier ligne de deuxieme matrice
arr[0][0][0] #Premier element du premier matrice au premier ligne

1

In [22]:
sub=arr[1][0]
sub[0]=0
arr
# reference: sub est un pointeur vers la ligne de arr ce qui explique le changement de valeur de tab original


array([[[1, 2, 7],
        [3, 4, 8]],

       [[0, 9, 2],
        [5, 3, 1]]])

## Indexation negative

In [26]:
arr[-1,-2]

array([0, 9, 2])

## NDARRAY SLICING

In [42]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[2:5]
arr[2:5:2]
arr[8:2:-1]
print(arr[-2:1:-2])


[7 5 3]


In [44]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[1,1:3]

array([6, 7])

In [57]:
arr[1:,1:3]

arr[::2,1:3]

array([[ 2,  3],
       [10, 11]])

In [61]:
arr[[0,2],1:3]

array([[ 2,  3],
       [10, 11]])

In [64]:
arr[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [66]:
arr[-2:,-3:]

array([[ 6,  7,  8],
       [10, 11, 12]])

# Type de donnees dans Numpy


- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- o - object
- s - string
- u - unicode string
- v - fixed chunk of memory for other type


In [67]:
arr.dtype

dtype('int64')

In [69]:
arr= np.array(["un","deux","trois"])
arr.dtype

dtype('<U5')

In [71]:
arr=np.array([1,2,3,4],dtype='i')
arr.dtype
# important

dtype('int32')

On peut aussi definir la taille pour i,u,f,s et u

In [72]:
arr=np.array([1,2,3,4],dtype='i1')
arr.dtype

dtype('int8')

In [73]:
arr=np.array(['1','2','3','4'],dtype='i1')
arr.dtype

dtype('int8')

# Converstion du type de donnees


In [78]:
arr=np.array([1.1,2.1,3.1])
new = arr.astype(str) # int,bool,float,'i','S','f'
new # Cree un nouveau tableau
arr

# verifier que le tableau est authentic (recupere la source de donnees)
print(new.base)


None


# Copie et vue d'un ndarray (Copy vs View)

- copie : nouveau tableau
- view : vue du tableau d'origin

In [80]:
arr= np.array([1,2,3,4,5])
x= arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [81]:
arr= np.array([1,2,3,4,5])
x= arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [95]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
z=arr[1:3]
u=arr # not authentic because it is the same arr with another name
print(arr.base)#authentic
print(x.base)#authentic
print(y.base)
print(z.base)
print(u.base)


None
None
[1 2 3 4 5]
[1 2 3 4 5]
None


# Forme d'un ndarray(shape)

In [98]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr.shape

(3, 4)

In [109]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

arr.shape


(3, 2, 2)

In [105]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]).reshape(2,3,2)
#2 ,3,2    [[[1,2],[ 3,4],[ 5,6]],[[ 7,8],[ 9,10],[11,12]]]
#3,4   [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
#3,4,1 [[[1],[2],[3],[4]],[[5],[6],[7],[8]],[[9],[10],[11],[12]]]
#4,1,3,1 [[[[1],[2],[3]]],[[[4],[5],[6]]],[[[7],[8],[9]]],[[[10],[11],[12]]]]
#12,1,1 [[[1]],[[2]],[[3]],[[4]],[[5]],[[6]],[[7]],[[8]],[[9]],[[10]],[[11]],[[12]]]

In [119]:
np.array([[[1]],[[2]],[[3]],[[4]],[[5]],[[6]],[[7]],[[8]],[[9]],[[10]],[[11]],[[12]]]).shape

(12, 1, 1)

# Parcourir les elements d'un ndarray

In [3]:
arr= np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [9]:
#sum des element de arr
arr=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
#1
s=0
for x in arr.reshape(-1):
    s+=x
print(s)
#2
arr.sum()


45


45

In [10]:
for idx,x in np.ndenumerate(arr): #get indices and values
    print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 0, 2) 6
(2, 0, 0) 7
(2, 0, 1) 8
(2, 0, 2) 9


# Jointure des ndarray


In [13]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
arr= np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
arr1= np.array([[1,2],[3,4]])
arr2= np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2),axis=1)


In [31]:
arr1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr2=np.array([[[9,10],[11,12]],[[13,14],[15,16]]])
arr= np.concatenate((arr1,arr2))
print(arr)
print(arr.shape)
print("-----------------------")
arr=arr = np.concatenate((arr1,arr2),axis=1)
print(arr)
print(arr.shape)
print("-----------------------")
arr=arr = np.concatenate((arr1,arr2),axis=2)
print(arr)
print(arr.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
-----------------------
[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]
(2, 4, 2)
-----------------------
[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]
(2, 2, 4)


# Fonction Stack

difference est que se fait le long d'un nouveau stack

In [34]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [37]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [39]:
arr1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr2=np.array([[[9,10],[11,12]],[[13,14],[15,16]]])
arr= np.stack((arr1,arr2))
print(arr)
print(arr.shape)
print("-----------------------")
arr=arr = np.stack((arr1,arr2),axis=1)
print(arr)
print(arr.shape)
print("-----------------------")
arr=arr = np.stack((arr1,arr2),axis=2)
print(arr)
print(arr.shape)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
(2, 2, 2, 2)
-----------------------
[[[[ 1  2]
   [ 3  4]]

  [[ 9 10]
   [11 12]]]


 [[[ 5  6]
   [ 7  8]]

  [[13 14]
   [15 16]]]]
(2, 2, 2, 2)
-----------------------
[[[[ 1  2]
   [ 9 10]]

  [[ 3  4]
   [11 12]]]


 [[[ 5  6]
   [13 14]]

  [[ 7  8]
   [15 16]]]]
(2, 2, 2, 2)


In [ ]:
# vstack
#dstack

# Fractionnner un ndarray

In [42]:
arr = np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
newarr # list des ndarray


[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [47]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.array_split(arr,2,axis=1)
newarr

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14],
        [16, 17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

# Recherche dans un ndarray

In [55]:
arr = np.array([1,2,3,4,5,4,4])
x=np.where(arr>0)
print(x)
print(arr[x])

(array([0, 1, 2, 3, 4, 5, 6]),)
[1 2 3 4 5 4 4]


In [56]:
#search sorted

# Trier les ndarray

In [57]:
arr=np.array([3,2,0,1])
v=np.sort(arr)
v

array([0, 1, 2, 3])

In [78]:
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr,axis=1))
print(np.sort(arr,axis=0))

[[2 3 4]
 [0 1 5]]
[[3 0 1]
 [5 2 4]]


# Filtrer les elements de ndarray

In [79]:
arr=np.array([1,2,1,4,2])
x=[True,False,True,False,True]
newarr=arr[x]
print(newarr)


[1 1 2]


In [81]:
u=arr>3
u

array([False, False, False,  True, False])

In [126]:
#exercice 

#get clean data and removing header
data=pd.read_csv("dog_intelligence.csv",header=None)
arraydata=data.values[1:,:-2]
print(arraydata)


#cleaning data
arraydata.shape

# total of brightest dogs
print(arraydata[arraydata[:,2]=="Brightest Dogs"][])
print(arraydata[arraydata[:,2]=="Brightest Dogs"].shape)



[['0' 'Border Collie' 'Brightest Dogs' '95%']
 ['1' 'Poodle' 'Brightest Dogs' '95%']
 ['2' 'German Shepherd' 'Brightest Dogs' '95%']
 ['3' 'Golden Retriever' 'Brightest Dogs' '95%']
 ['4' 'Doberman Pinscher' 'Brightest Dogs' '95%']
 ['5' 'Shetland Sheepdog' 'Brightest Dogs' '95%']
 ['6' 'Labrador Retriever' 'Brightest Dogs' '95%']
 ['7' 'Papillon' 'Brightest Dogs' '95%']
 ['8' 'Rottweiler' 'Brightest Dogs' '95%']
 ['9' 'Australian Cattle Dog' 'Brightest Dogs' '95%']
 ['10' 'Pembroke Welsh Corgi' 'Excellent Working Dogs' '85%']
 ['11' 'Miniature Schnauzer' 'Excellent Working Dogs' '85%']
 ['12' 'English Springer Spaniel' 'Excellent Working Dogs' '85%']
 ['13' 'Belgian Shepherd Dog (Tervuren)' 'Excellent Working Dogs' '85%']
 ['14' 'Schipperke' 'Excellent Working Dogs' '85%']
 ['15' 'Belgian Sheepdog' 'Excellent Working Dogs' '85%']
 ['16' 'Collie' 'Excellent Working Dogs' '85%']
 ['17' 'Keeshond' 'Excellent Working Dogs' '85%']
 ['18' 'German Shorthaired Pointer' 'Excellent Working Dogs

# Ufuncs

In [129]:
x=[1,2,3,4]
y=[4,5,6,7]
z=[]


def add(x,y):
    return x+y
addArr=np.frompyfunc(add,2,1)#function 2 parameters 1 output
print(addArr([1,2,3,4],[4,5,6,7]))
print(type(addArr))

[5 7 9 11]
<class 'numpy.ufunc'>


 predefined ufuncs
- np.add
- np.substr
- np.mod
- np.divide
- np.power
- np.remainder
- np.absolute

In [3]:
u=np.array([101,-11,12,-13,14,15])
print(np.sum(np.multiply(u,u))) 

11056


In [4]:
np.absolute(u)

array([101,  11,  12,  13,  14,  15])

# Arrondir les decimales


- truncation
- fix
- rounding
- floor
- ceil

In [5]:
arr = np.array([-3.1645,3.6667])
a=np.trunc(arr)
print(a)
a=np.fix(arr)
print(a)
a=np.trunc(arr)
print(a)
a=np.trunc(arr)
print(a)#

[-3.  3.]


In [6]:
arr1=np.array([1,2,3])
arr2=np.array([1,12,3])

newarr=np.sum([arr1,arr2])
print(np.log(arr1))


[0.         0.69314718 1.09861229]


In [7]:
# sum by axis
arr1=np.array([1,2,3])
arr2=np.array([1,2,3])
mat=[arr1,arr2]

newarr=np.sum(mat)
print(mat)
print(newarr)
print("****************")
newarr=np.sum(mat,axis=0)
print(mat)
print(newarr)
print("****************")
newarr=np.sum(mat,axis=1)
print(mat)
print(newarr)

[array([1, 2, 3]), array([1, 2, 3])]
12
****************
[array([1, 2, 3]), array([1, 2, 3])]
[2 4 6]
****************
[array([1, 2, 3]), array([1, 2, 3])]
[6 6]


In [ ]:
arr = np.array([1,2,3])
newarr = np.cum

In [ ]:
#diff

In [9]:
from numpy import random


# Distribution binomial


In [10]:
x= random.binomial(n=10,p=0.5,size=100)
print(x)

[8 7 5 6 3 6 5 5 4 7 6 5 6 6 6 6 3 4 8 5 7 7 4 7 5 7 5 2 3 6 7 6 4 7 7 6 4
 5 6 3 6 7 5 4 3 7 5 4 5 8 5 7 5 8 5 2 5 7 5 4 5 8 5 3 2 6 3 3 4 4 5 2 5 3
 6 6 2 5 7 5 6 5 4 6 7 7 5 5 7 3 7 4 6 5 3 7 5 6 5 2]


In [11]:
import seaborn as sns


# Distribution uniforme