## Indexation normale

In [2]:
import numpy as np

In [8]:
arr= np.array([[[1,2,7],[3,4,8]],[[4,9,2],[5,3,1]]])
arr.ndim
arr[1] # deuxieme matrice
arr[1][0] # premier ligne de deuxieme matrice
arr[0][0][0] #Premier element du premier matrice au premier ligne

1

In [22]:
sub=arr[1][0]
sub[0]=0
arr
# reference: sub est un pointeur vers la ligne de arr ce qui explique le changement de valeur de tab original


array([[[1, 2, 7],
        [3, 4, 8]],

       [[0, 9, 2],
        [5, 3, 1]]])

## Indexation negative

In [26]:
arr[-1,-2]

array([0, 9, 2])

## NDARRAY SLICING

In [42]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[2:5]
arr[2:5:2]
arr[8:2:-1]
print(arr[-2:1:-2])


[7 5 3]


In [44]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[1,1:3]

array([6, 7])

In [57]:
arr[1:,1:3]

arr[::2,1:3]

array([[ 2,  3],
       [10, 11]])

In [61]:
arr[[0,2],1:3]

array([[ 2,  3],
       [10, 11]])

In [64]:
arr[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [66]:
arr[-2:,-3:]

array([[ 6,  7,  8],
       [10, 11, 12]])

# Type de donnees dans Numpy


- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- o - object
- s - string
- u - unicode string
- v - fixed chunk of memory for other type


In [67]:
arr.dtype

dtype('int64')

In [69]:
arr= np.array(["un","deux","trois"])
arr.dtype

dtype('<U5')

In [71]:
arr=np.array([1,2,3,4],dtype='i')
arr.dtype
# important

dtype('int32')

On peut aussi definir la taille pour i,u,f,s et u

In [72]:
arr=np.array([1,2,3,4],dtype='i1')
arr.dtype

dtype('int8')

In [73]:
arr=np.array(['1','2','3','4'],dtype='i1')
arr.dtype

dtype('int8')

# Converstion du type de donnees


In [78]:
arr=np.array([1.1,2.1,3.1])
new = arr.astype(str) # int,bool,float,'i','S','f'
new # Cree un nouveau tableau
arr

# verifier que le tableau est authentic (recupere la source de donnees)
print(new.base)


None


# Copie et vue d'un ndarray (Copy vs View)

- copie : nouveau tableau
- view : vue du tableau d'origin

In [80]:
arr= np.array([1,2,3,4,5])
x= arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [81]:
arr= np.array([1,2,3,4,5])
x= arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [95]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
z=arr[1:3]
u=arr # not authentic because it is the same arr with another name
print(arr.base)#authentic
print(x.base)#authentic
print(y.base)
print(z.base)
print(u.base)


None
None
[1 2 3 4 5]
[1 2 3 4 5]
None


# Forme d'un ndarray(shape)

In [98]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr.shape

(3, 4)

In [109]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

arr.shape


(3, 2, 2)

In [105]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]).reshape(2,3,2)
#2 ,3,2    [[[1,2],[ 3,4],[ 5,6]],[[ 7,8],[ 9,10],[11,12]]]
#3,4   [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
#3,4,1 [[[1],[2],[3],[4]],[[5],[6],[7],[8]],[[9],[10],[11],[12]]]
#4,1,3,1 [[[[1],[2],[3]]],[[[4],[5],[6]]],[[[7],[8],[9]]],[[[10],[11],[12]]]]
#12,1,1 [[[1]],[[2]],[[3]],[[4]],[[5]],[[6]],[[7]],[[8]],[[9]],[[10]],[[11]],[[12]]]

In [119]:
np.array([[[1]],[[2]],[[3]],[[4]],[[5]],[[6]],[[7]],[[8]],[[9]],[[10]],[[11]],[[12]]]).shape

(12, 1, 1)